CREATE TABLE IF NOT EXISTS gift_certificates (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(1000) DEFAULT NULL,
  price DECIMAL(10,2) NOT NULL,
  duration INT NOT NULL,
  create_date DATETIME NOT NULL,
  last_update_date DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS tags (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 username varchar(100) NOT NULL UNIQUE,
 password varchar(100) NOT NULL,
 role enum('USER','ADMIN')
);

CREATE TABLE IF NOT EXISTS m2m_gift_certificates_tags (
  gift_certificate_id BIGINT NOT NULL,
  tag_id BIGINT NOT NULL,
  PRIMARY KEY (`gift_certificate_id`, `tag_id`)
);

CREATE TABLE IF NOT EXISTS orders (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 price DECIMAL(10,2) NOT NULL,
 purchase_time DATETIME NOT NULL,
 user_id BIGINT NOT NULL,
 gift_certificate_id BIGINT NOT NULL,

 FOREIGN KEY (`user_id`) REFERENCES users (id),
 FOREIGN KEY (`gift_certificate_id`) REFERENCES gift_certificates (`id`)
);

-- Auditing tables

CREATE TABLE IF NOT EXISTS revinfo
(
    rev BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 ),
    revtstmp BIGINT,
    PRIMARY KEY ( rev )
);

CREATE TABLE IF NOT EXISTS gift_certificates_AUD
(
    id      BIGINT NOT NULL,
    REV     BIGINT NOT NULL,
    name VARCHAR(100),
    description VARCHAR(1000),
    price DECIMAL(10,2),
    duration INT,
    create_date DATETIME,
    last_update_date DATETIME,
    REVTYPE TINYINT,
    PRIMARY KEY ( id, REV ),
    FOREIGN KEY ( REV ) REFERENCES revinfo (rev)
);

CREATE TABLE IF NOT EXISTS orders_AUD
(
    id      BIGINT NOT NULL,
    REV     BIGINT NOT NULL,
    price DECIMAL(10,2),
    purchase_time DATETIME,
    REVTYPE TINYINT,
    user_id BIGINT NOT NULL,
    gift_certificate_id BIGINT NOT NULL,
    PRIMARY KEY ( id, REV ),
    FOREIGN KEY ( REV ) REFERENCES revinfo (rev)

);

CREATE TABLE IF NOT EXISTS tags_AUD
(
    id      BIGINT NOT NULL,
    REV     BIGINT NOT NULL,
    name varchar(100),
    REVTYPE TINYINT,
    PRIMARY KEY ( id, REV ),
    FOREIGN KEY ( REV ) REFERENCES revinfo (rev)

);

CREATE TABLE IF NOT EXISTS users_AUD
(
    id      BIGINT NOT NULL,
    REV     BIGINT NOT NULL,
    username varchar(100),
    password varchar(100),
    role enum('USER','ADMIN'),
    REVTYPE TINYINT,
    PRIMARY KEY ( id, REV ),
    FOREIGN KEY ( REV ) REFERENCES revinfo (rev)

);